### ISSUE TITLE
Feed display issue

### ISSUE THREAD

**Issue by cfederman** [scripting/feedlandSupport#194] opened 2023-04-23 14:51 UTC
Hi Dave,

we met many years ago in Berkeley with Gordon E. Thanks for creating Feedland, I’ve been enjoying the freedom to create and discover a relevant news channel. I’ve been having an issue with displaying the feed, for some reason, on my iPad, running iOS 16.4.1, the feed does not displaysand after a minute or two a communication error is displayed. It happens 90% of the time…not 100%….I took screen shots that I hope will be helpful.

thanks

![IMG_0771](https://user-images.githubusercontent.com/1440064/233846772-9dd00b10-e555-4bac-a6d8-efb01601515f.png)
![IMG_0770](https://user-images.githubusercontent.com/1440064/233846773-a4dcaf85-73bd-42e1-a8cc-af96481dde4b.png)
![IMG_0769](https://user-images.githubusercontent.com/1440064/233846774-8f8000fd-2790-4ba5-862f-8eec671cea2f.png)

**Comment by scripting** [comment] 2023-04-23 14:54
@cfederman -- Please explain simply, in words, exactly what you did. What commands you used, what data you entered, so we can reproduce it here. 

Also please -- if you make it personal, other people won't chime in to help if they can. I hold out hope someday other people will help out with supporting new users. Thanks.

**Comment by cfederman** [comment] 2023-04-23 15:09
Hi,I’ve been using the product since shortly after the release and this issue (news feed not displaying) surfaced a few weeks ago sporadically, but is now standard. I haven’t seen others speak about it in the forum yet.In Safari I entered feedland.org which brought me to this  https://feedland.org/?riverI see only the Feedland header, until the communication error message displayed below is messaged. I am able to display the feed list and when pressing on the ‘wedge’ in that list individual feeds are displayed. On Apr 23, 2023, at 10:54 AM, Dave Winer ***@***.***> wrote:﻿
@cfederman -- Please explain simply, in words, exactly what you did. What commands you used, what data you entered, so we can reproduce it here.
Also please -- if you make it personal, other people won't chime in to help if they can. I hold out hope someday other people will help out with supporting new users. Thanks.

**Comment by scripting** [comment] 2023-04-23 15:40
You may have to create a new account, because we switched over to a new identity system because Twitter was changing how things work, and eventually turned us off (last week actually, which is why you may be seeing things work differently now).

So you should try signing off, when you get a chance, and you should get a chance to create a new account, which you should do. We did have a transition period of a couple of months, but some people missed that, and they're showing up and surprised when things don't work.

You may need to resubscribe to your feeds, but that actually is pretty easy. 

If your previous account was "bullmancuso", you can get the OPML subscription list for that user with this URL.

https://feedland.org/opml?screenname=bullmancuso

Then if you want to subscribe to those feeds, just choose the command from the first menu, and enter that URL. 

It'll figure out what to do. :smile:

I'm also posting this here so the users who are tuned in know what to do so perhaps they can make note of this and help other users. ;-)

**Comment by cfederman** [comment] 2023-04-23 15:46
Thanks Dave, hope finding the issue makes it easier, going forward, for others. On Apr 23, 2023, at 11:40 AM, Dave Winer ***@***.***> wrote:﻿
You may have to create a new account, because we switched over to a new identity system because Twitter was changing how things work, and eventually turned us off (last week actually, which is why you may be seeing things work differently now).
So you should try signing off, when you get a chance, and you should get a chance to create a new account, which you should do. We did have a transition period of a couple of months, but some people missed that, and they're showing up and surprised when things don't work.
You may need to resubscribe to your feeds, but that actually is pretty easy.
If your previous account was "bullmancuso", you can get the OPML subscription list for that user with this URL.
https://feedland.org/opml?screenname=bullmancuso
Then if you want to subscribe to those feeds, just choose the command from the first menu, and enter that URL.
It'll figure out what to do. 😄
I'm also posting this here so the users who are tuned in know what to do so perhaps they can make note of this and help other users. ;-)

**Comment by cfederman** [comment] 2023-04-24 12:52
Dave,As suggested, I set up a new account and am experiencing the same issue. CharlieOn Apr 23, 2023, at 11:00 PM, Dave Winer ***@***.***> wrote:﻿
To everyone else -- I'm now having this problem too, and a quick look didn't reveal what it is. I'll be looking at this more closely tomorrow.

**Comment by scripting** [comment] 2023-04-24 13:30
As promised I am looking into this and it's a problem with a query in the database taking a very long time to run. 

Stay tuned...

**Comment by scripting** [comment] 2023-04-25 02:32
BTW, anyone who sees this problem, where FeedLand times out trying to get you your main news river...

There is a workaround -- 

1. In Settings.
2. First panel.
3. Make sure you have two or more categories on the home page. 

Like so.

![image](https://user-images.githubusercontent.com/1686843/234160313-67e0bce5-21ae-46a5-930e-4d40d834f85d.png)

**Comment by scripting** [comment] 2023-04-25 18:22
@cfederman et al.

I believe this problem is fixed now. You should now be able to view your news without the previous timeout.

**Closed by scripting** 2023-04-25 18:22 UTC
